# Generated by Django 5.0 on 2024-10-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_join',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('member', 'Member'), ('alumni', 'Alumni'), ('president', 'president')], default='member', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
