# Generated by Django 5.0 on 2024-10-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examportal', '0002_student_date_join_student_student_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_join',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('deputy', 'vice leader'), ('member', 'Member'), ('alumni', 'Alumni'), ('president', 'president')], default='member', max_length=100),
        ),
    ]
